# Generated by Django 5.1.1 on 2024-11-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_hotel_address_en_hotel_address_ru_hotel_city_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='hotel_stars',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
